package ba.unsa.etf.rpr.business;


import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Category;
import ba.unsa.etf.rpr.exceptions.MarketException;

/**
 * Business Logic Layer for management of Categories
 *
 * @author Ernad Zuga
 */

public class CategoryManager {
    public void validateCategoryName(String name) throws MarketException {
        if(name == null || name.length() > 45 || name.length() <3){
            throw new MarketException("Category name must be between 3 and 45 chars");
        }

    }
    public Category add(Category cat) throws MarketException {
        if(cat.getId() != 0){
            throw new MarketException("Can't add category with ID. ID is autogenerated");
        }
        validateCategoryName(cat.getName());

        try {
            return DaoFactory.categoryDao().add(cat);

        }catch (MarketException e){
            if(e.getMessage().contains("UQ_NAME")){
                throw new MarketException("Category with same name exists");
            }
            throw e;
        }
    }

    public void delete(int categoryId) throws MarketException {
        try{
            DaoFactory.categoryDao().delete(categoryId);
        } catch (MarketException e) {
            if(e.getMessage().contains("FOREIGN KEY")){
                throw new MarketException("Cannot delete category which is related to items. First delete related items before deleting category");
            }
            throw e;
    }
}
